### ISSUE TITLE
File size exceeded achievements.json

### ISSUE THREAD

**Issue by sparroha** [wyldmods/SimpleAchievements#5]
All of your achievement records are stored inside a single json file. This creates a limitation of how many players are allowed to play on the server before the server crashed.
This limitation is based on the amount of achievements configured in the config folder and the number of players that are being actively recorded in achievements.json within the world folder.

the crash log depicts a file size of 56424. I confirmed that my file has 56423 visible lines of json entry. I suggest changing your storage method to seperate each player into their own personal achievement.json. i.e.: world/SimpleAchievements/playername.json

here is the crash:

Time: 5/13/15 6:59 PM
Description: Exception in server tick loop

com.google.gson.JsonSyntaxException: java.io.EOFException: End of input at line 56424 column 1
	at com.google.gson.Gson.fromJson(Gson.java:813)
	at com.google.gson.Gson.fromJson(Gson.java:768)
	at com.google.gson.Gson.fromJson(Gson.java:717)
	at org.wyldmods.simpleachievements.common.data.DataManager.loadMap(DataManager.java:184)
	at org.wyldmods.simpleachievements.common.data.DataManager.load(DataManager.java:133)
	at org.wyldmods.simpleachievements.common.data.DataManager.onWorldLoad(DataManager.java:41)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_358_DataManager_onWorldLoad_Load.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:431)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:335)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException: End of input at line 56424 column 1
	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1377)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:483)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:403)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:166)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.Gson.fromJson(Gson.java:803)
	... 12 more

**Comment by tterrag1098** [comment]
Yes, this issue was rectified in the latest build. Update and the data
should be converted to the latest version.
